// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZz8_t05ANo2kbx8Gzq26XPmaQ8S_CIks',
    appId: '1:908770202818:web:01a82a6160f638f0a0575b',
    messagingSenderId: '908770202818',
    projectId: 'realtime-storage-9caf0',
    authDomain: 'realtime-storage-9caf0.firebaseapp.com',
    databaseURL: 'https://realtime-storage-9caf0-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-storage-9caf0.appspot.com',
    measurementId: 'G-DLQNHEZK7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVxCKGAiiiR2g7ovGxU4pF1wg6VQMmIEI',
    appId: '1:908770202818:android:5e2609c53dd2498ea0575b',
    messagingSenderId: '908770202818',
    projectId: 'realtime-storage-9caf0',
    databaseURL: 'https://realtime-storage-9caf0-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-storage-9caf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_AUZmeHIXN9QXgEj1rMg9okA_rTRoN9E',
    appId: '1:908770202818:ios:74eaf897b6a24214a0575b',
    messagingSenderId: '908770202818',
    projectId: 'realtime-storage-9caf0',
    databaseURL: 'https://realtime-storage-9caf0-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-storage-9caf0.appspot.com',
    iosBundleId: 'com.example.realtimeStorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_AUZmeHIXN9QXgEj1rMg9okA_rTRoN9E',
    appId: '1:908770202818:ios:0725f10b037145eca0575b',
    messagingSenderId: '908770202818',
    projectId: 'realtime-storage-9caf0',
    databaseURL: 'https://realtime-storage-9caf0-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-storage-9caf0.appspot.com',
    iosBundleId: 'com.example.realtimeStorage.RunnerTests',
  );
}
